# Generated by Django 2.0.5 on 2018-07-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='users',
            new_name='user',
        ),
    ]
